### ISSUE TITLE
Could you add the license for this application?

### ISSUE THREAD

**Issue by fakeskimo** [hjmangalam/parsyncfp#17]
Hello!!

First of all, thank you for this great application. I am considering to use the parsyncfp at work but before start to use it, I need accurate license information for your work.

I would like you ask you to add the license to parsyncfp. After that I can use it with clear understanding of license. Let me know when you made mind what license will be.

Thanks,

**Comment by hjmangalam** [comment]
Hmm - that's an oversight - I'll try to get to this later today. The rest of my stuff is GPL3, 
but I have to see if there are any updates.

Thanks for the note.

hjm

On Tuesday, March 19, 2019 7:16:48 AM PDT fakeskimo wrote:
> Hello!!
> 
> First of all, thank you for this great application. I am considering to
> use the parsyncfp at work but before start to use it, I need accurate
> license information for your work.
> 
> I would like you ask you to add the license to parsyncfp. After that I
> can use it with clear understanding of license. Let me know when you
> made mind what license will be.
> 
> Thanks,



Harry Mangalam, 
Info[1] 

--------
[1] http://moo.nac.uci.edu/~hjm/hjm.sig.html

**Comment by fakeskimo** [comment]
Thank you for the comment. I am looking forward to test your application soon. 😄

**Comment by hjmangalam** [comment]
On Wednesday, March 20, 2019 5:20:05 PM PDT fakeskimo wrote:
> Thank you for the comment. I am looking forward to test your application
> soon. 😄 
 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/hjmangalam/parsyncfp/issues/17#issuecomment-475076772

OK - COPYRIGHT file included, some minor updates to docs, etc.

hjm-- 
Harry Mangalam, 
Info[1] 

--------
[1] http://moo.nac.uci.edu/~hjm/hjm.sig.html

**Comment by fakeskimo** [comment]
Thank you again for adding clear license information. 👍  I will close this issue because there is no further action required at this point. Thanks!

**Comment by hjmangalam** [comment]
On Wednesday, March 27, 2019 11:02:28 AM PDT fakeskimo wrote:
> Thank you again for adding clear license information. 👍 I will close
> this issue because there is no further action required at this point.
> Thanks!

Thanks.  Let me know if there are other things you need clarity on or help with.

hjm


Harry Mangalam, 
Info[1] 

--------
[1] http://moo.nac.uci.edu/~hjm/hjm.sig.html
