### ISSUE TITLE
What version of Perl is required?

### ISSUE THREAD

**Issue by jaytaylor** [hjmangalam/parsyncfp#22]
When I try to run parsyncfp:

```bash
Can't locate Env.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./parsyncfp line 12.
BEGIN failed--compilation aborted at ./parsyncfp line 12.

perl --version

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 39 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

```

**Comment by jaytaylor** [comment]
Nevermind, solved with the help of [SO](https://superuser.com/questions/1181310/perl-script-cant-locate-env-pm-in-inc):

```bash
sudo yum install perl-Env
```

Thanks for making parsyncfp!

**Comment by hjmangalam** [comment]
Note the bug about the suspend/unsuspend.  I'm closing in on fixing it, but haven't 
finalized it yet.

hjm

On Tuesday, June 4, 2019 2:56:50 PM PDT J. Elliot Taylor wrote:
> Nevermind, solved with the help of
> [SO](https://superuser.com/questions/1181310/perl-script-cant-locate-env
> -pm-in-inc):
> 
> ```bash
> sudo yum install perl-Env
> ```
> 
> Thanks for making parsyncfp!



Harry Mangalam, 
Info[1] 

--------
[1] http://moo.nac.uci.edu/~hjm/hjm.sig.html

**Comment by jaytaylor** [comment]
Is the bug referencing is the machine is a laptop or VM and goes into suspend power mode?

**Comment by jaytaylor** [comment]
Is the bug referencing cases where the machine is a laptop or VM which then goes into suspend power mode?

**Comment by jaytaylor** [comment]
Oh, after reading the `--help` more, I understand.  I will set `--maxload` to 50 (nCPU=54).

Thanks @hjmangalam!

**Comment by hjmangalam** [comment]
On Tuesday, June 4, 2019 3:26:10 PM PDT J. Elliot Taylor wrote:
> Oh, after reading the `--help` more, I understand.  I will set
> `--maxload` to 50 (nCPU=54).
> 
> Thanks @hjmangalam!

Or set --maxload=400 to make sure it doesn't hit it.  Typically on a X core system, each 
rsync will take up about 1core's worth of load (depending on options, offload engines, 
etc).  Not actual cpu usage, but load (from loadavg).  Also, I've never used that high a 
number for pfp so I'd be interested in what advantage you see vs a lower (saner) number 
;)

Thanks for trying it.

hjm

 



Harry Mangalam, 
Info[1] 

--------
[1] http://moo.nac.uci.edu/~hjm/hjm.sig.html
