### ISSUE TITLE
Unable to specify a custom SSH port

### ISSUE THREAD

**Issue by youvegotmoxie** [hjmangalam/parsyncfp#28]
I'm trying to use parsyncfp on a host which listens on a non-standard SSH port. With rsync this can be done by using `--rsh="ssh -p $PORT`, however, when trying to use that within `--rsyncopts` parsyncfp tries to evaluate `-p` as a passed parameter which results in an error.

Do you have any suggestions on how I could accomplish this or perhaps add in support for this natively in the tool?

**Comment by hjmangalam** [comment]
While it may be a parsyncfp problem, it more probably sounds like a bash quoting 
problem.  Can you include the exact commandline you used to try this?

hjm

On Saturday, October 19, 2019 8:00:43 PM PDT Michael Beasley wrote:
> I'm trying to use parsyncfp on a host which listens on a non-standard SSH
> port. With rsync this can be done by using `--rsh="ssh -p $PORT`,
> however, when trying to use that within `--rsyncopts` parsyncfp tries to
> evaluate `-p` as a passed parameter which results in an error.
> 
> Do you have any suggestions on how I could accomplish this or perhaps add
> in support for this natively in the tool?



Harry Mangalam, 
Info[1] 

--------
[1] http://moo.nac.uci.edu/~hjm/hjm.sig.html

**Comment by hjmangalam** [comment]
Any follow-up on this? Happy to try to answer but I need the exact command.
