### ISSUE TITLE
how to select / system root as the starting point ?

### ISSUE THREAD

**Issue by MasterCATZ** [hjmangalam/parsyncfp#29]
every-time I try it is looking at the home folder of user 

looking for a way to make a system backup local  / to local /mnt 

./parsyncfp -v 2 --maxload=5.5 --NP=10 --rsyncopts="-aAXv --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","ZFSRaidz*","SnapRaid*","/lost+found"}" "--startdir=/"  /SnapRaidArray/DATA/Backup/Nov2019

**Comment by hjmangalam** [comment]
The rsync opts are up to you (and I'm not sure the rsync-options are going to work as 
you describe.  Not saying they won't but it doesn't work for me.  (Perhaps try the  -–
exclude-from option and provide a file of dirs to exclude?)

The main thing that you seem to be having trouble with is specifying the top-level dirs.

You can do this with [ --startdir=/ . ] which will include all the top-level dirs and then use 
the -–exclude-from [file] or you can use explicit names:
--startdir=/ bin opt  var boot  etc lib sbin home lib64 root  usr  # etc

Does that work for you?

hjm

On Monday, November 11, 2019 5:22:02 PM PST MasterCATZ wrote:
> every-time I try it is looking at the home folder of user
> 
> looking for a way to make a system backup local  / to local /mnt
> 
> 
> ./parsyncfp -v 2 --maxload=5.5 --NP=10 --rsyncopts="-aAXv
> --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/medi
> a/*","ZFSRaidz*","SnapRaid*","/lost+found"}" "--startdir=/" 
> /SnapRaidArray/DATA/Backup/Nov2019



Harry Mangalam, 
Info[1] 

--------
[1] http://moo.nac.uci.edu/~hjm/hjm.sig.html

**Comment by MasterCATZ** [comment]
THANK YOU 

--startdir=/ . 

that / space dot made all the difference :D

issue for me was all the small files this helped knock through the google cache fast
